# Generated by Django 3.1.4 on 2020-12-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fav_book_app', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
